import type { Metadata } from "next";
import { Quicksand,Maven_Pro, } from "next/font/google";
import "./globals.css";

const quicksand = Quicksand({ subsets: ["latin"], weight:['700','600'],variable:'--font-quicksand' });
const mavenpro  = Maven_Pro({ subsets: ["latin"],
  weight:['400','500'],
  variable:'--font-maven-pro'

 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} ${mavenpro.variable}`}>{children}

      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
      </body>
     
    </html>
  );
}
